---
- name: Install tilix
  dnf:
    name: tilix
    state: present
  become: yes
- name: Tilix theme color
  dconf:
    key: '/com/gexperts/Tilix/theme-variant'
    value: "'system'"
- name: Tilix scroll to zoom
  dconf:
    key: '/com/gexperts/Tilix/control-scroll-zoom'
    value: 'true'
- name: Tilix active titlebar highlighted
  blockinfile:
    path: '{{ ansible_user_dir }}/.config/gtk-3.0/gtk.css'
    marker: '/* {mark} ANSIBLE MANAGED BLOCK */'
    block: |
      .terminal-titlebar:active { background-color: #FC3A0D; }
