---
- name: Install tilix
  dnf:
    name: tilix
    state: present
  become: yes
- name: Tilix theme color
  dconf:
    key: '/com/gexperts/Tilix/theme-variant'
    value: "'system'"
- name: Tilix scroll to zoom
  dconf:
    key: '/com/gexperts/Tilix/control-scroll-zoom'
    value: 'true'
- name: Tilix clean terminal shortcut
  dconf:
    key: '/com/gexperts/Tilix/keybindings/terminal-reset-and-clear'
    value: "'<Primary><Shift>y'"
- name: Get Tilix default profile id
  dconf:
    key: '/com/gexperts/Tilix/profiles/default'
  register: tilix_default_profile_result
- name: 'Tilix scroll length to 32000 lines'
  dconf:
    key: '/com/gexperts/Tilix/profiles/{{ tilix_default_profile_result.value }}/scrollback-lines'
    value: '32000'
- name: Tilix active titlebar highlighted
  blockinfile:
    path: '{{ ansible_user_dir }}/.config/gtk-3.0/gtk.css'
    marker: '/* {mark} ANSIBLE MANAGED BLOCK */'
    block: |
      .terminal-titlebar:active { background-color: #FC3A0D; }
