- name: Microsoft packages key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: yes
- name: Visual Studio Code repo
  yum_repository:
    name: vscode # name of *.repo file and section header:q
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    description: "Visual Studio Code" # 'name' field inside the file
  become: yes
- name: Update dnf repo cache
  command: dnf check-update
  register: dnf_check_update_result
  failed_when: 'not dnf_check_update_result.rc in (0, 100)'
  become: yes
- name: Install Visual Studio Code
  dnf:
    name: code
    state: present
  become: yes
- name: Create VS Code config dir
  file:
    path: '{{ ansible_user_dir }}/.config/Code/User'
    state: 'directory'
- name: Create default VS Code config
  copy:
    force: no
    dest: '{{ ansible_user_dir }}/.config/Code/User/settings.json'
    content: '{}'
- name: 'Set VS Code settings fact'
  set_fact:
    vs_code_settings: |
      {
        "files.autoSave": "onFocusChange",
        "window.zoomLevel": 0,
        "editor.mouseWheelZoom": true,
        "javascript.validate.enable": false
      }
- name: 'Update VS Code settings'
  copy:
    dest: '{{ ansible_user_dir }}/.config/Code/User/settings.json'
    content: |
      {{
        lookup('file', ansible_user_dir + '/.config/Code/User/settings.json')
        | regex_findall('.*')
        | select('regex', '^\s*[^/]')
        | list
        | join
        | from_json
        | combine(vs_code_settings | from_json , recursive=True)
        | to_nice_json
      }}
- name: Create default VS Code keybindings confg
  copy:
    force: no
    dest: '{{ ansible_user_dir }}/.config/Code/User/keybindings.json'
    content: '[]'
- name: 'Set VS Code keybindings fact'
  set_fact:
    vs_code_keybindings: |
      [
        {
            "key": "ctrl+d",
            "command": "editor.action.copyLinesDownAction",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+alt+down",
            "command": "-editor.action.copyLinesDownAction",
            "when": "editorTextFocus && !editorReadonly"
        }
      ]
- name: 'Update VS Code keybindings'
  copy:
    dest: '{{ ansible_user_dir }}/.config/Code/User/keybindings.json'
    content: >
      {{
        lookup('file', ansible_user_dir + '/.config/Code/User/keybindings.json')
        | regex_findall('.*')
        | select('regex', '^\s*[^/]')
        | list
        | join
        | from_json
        | union( vs_code_keybindings | from_json )
        | to_nice_json
      }}
- name: 'Install VS Code Flow extension'
  command: 'code --install-extension flowtype.flow-for-vscode'
  changed_when: "not last_result.stdout | search('already installed')"
  register: last_result
- name: 'Install VS Code Git Lens extension'
  command: 'code --install-extension eamodio.gitlens'
  changed_when: "not last_result.stdout | search('already installed')"
  register: last_result
- name: 'Install VS Code XML Tools extension'
  command: 'code --install-extension DotJoshJohnson.xml'
  changed_when: "not last_result.stdout | search('already installed')"
  register: last_result
- name: 'Install VS Code Editor Config extension'
  command: 'code --install-extension EditorConfig.EditorConfig'
  changed_when: "not last_result.stdout | search('already installed')"
  register: last_result
- name: 'Install VS Code Python extension'
  command: 'code --install-extension ms-python.python'
  changed_when: "not last_result.stdout | search('already installed')"
  register: last_result
