---
- name: checking variable file
  fail:
    msg: Please fill in variable file for this role
  when: not rh_nick
- name: git clone
  git:
    repo: "{{ url }}"
    dest: "{{ dest_dir }}"
    update: no
- name: add change id hook
  get_url:
    url: 'https://gerrit.ovirt.org/tools/hooks/commit-msg'
    dest: '{{ dest_dir }}/.git/hooks'
    force: no
    mode: 'u=rwx,g=r,o=r'
- name: sign off by
  blockinfile:
    path: "{{ dest_dir }}/.git/hooks/commit-msg"
    insertafter: EOF
    block: |
      SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
      grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

